import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { analyticsData } from '../../data/mockData'

const tooltipStyle = { border: '1px solid #dce5ee', borderRadius: 8, fontSize: 12 }
export function AnalyticsCharts({ compact = false }: { compact?: boolean }) {
  const charts = [
    <article className="panel chart-panel" key="vehicle"><div className="panel-heading"><div><p className="eyebrow">Prototype signal</p><h2>Vehicle Count</h2></div></div><ResponsiveContainer width="100%" height={compact ? 210 : 260}><AreaChart data={analyticsData.vehicleCount}><defs><linearGradient id="vehicleFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#316b9e" stopOpacity={.3}/><stop offset="100%" stopColor="#316b9e" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="timestamp"/><YAxis/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="count" name="Vehicles" stroke="#316b9e" strokeWidth={2.5} fill="url(#vehicleFill)"/></AreaChart></ResponsiveContainer></article>,
    <article className="panel chart-panel" key="density"><div className="panel-heading"><div><p className="eyebrow">Prototype signal</p><h2>Traffic Density</h2></div></div><ResponsiveContainer width="100%" height={compact ? 210 : 260}><BarChart data={analyticsData.trafficDensity}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="zone"/><YAxis/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="density" name="Density index" fill="#557f6c" radius={[5, 5, 0, 0]}/></BarChart></ResponsiveContainer></article>,
    <article className="panel chart-panel" key="congestion"><div className="panel-heading"><div><p className="eyebrow">Prototype signal</p><h2>Congestion Trend</h2></div></div><ResponsiveContainer width="100%" height={compact ? 210 : 260}><LineChart data={analyticsData.congestionTrend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time"/><YAxis/><Tooltip contentStyle={tooltipStyle}/><Line type="monotone" dataKey="index" name="Congestion index" stroke="#8564c5" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></article>,
    <article className="panel chart-panel" key="defects"><div className="panel-heading"><div><p className="eyebrow">Prototype signal</p><h2>Road Defect Detections</h2></div></div><ResponsiveContainer width="100%" height={compact ? 210 : 260}><BarChart data={analyticsData.roadDefects}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date"/><YAxis/><Tooltip contentStyle={tooltipStyle}/><Legend iconSize={9}/><Bar dataKey="potholes" name="Potholes" stackId="a" fill="#dc7b51"/><Bar dataKey="roadDamage" name="Road damage" stackId="a" fill="#dfb34f" radius={[4, 4, 0, 0]}/></BarChart></ResponsiveContainer></article>,
  ]
  return <div className="chart-grid">{charts}</div>
}
